-- 2479586_souptik

SHOW DATABASES;
CREATE DATABASE HANDSON;
USE HANDSON;

CREATE TABLE EMPLOYEE(
	EMPID INT,
    EMPNAME VARCHAR(255),
    SALARY INT,
    DEPT VARCHAR(255),
    CONSTRAINT PK PRIMARY KEY(EMPID)
);

-- 2479586_souptik
INSERT INTO EMPLOYEE VALUES 
	(001, 'EMPLOYEE_001', 45000, 'HR'),
	(002, 'EMPLOYEE_002', 52000, 'FINANCE'),
	(003, 'EMPLOYEE_003', 60000, 'IT'),
	(004, 'EMPLOYEE_004', 48000, 'MARKETING'),
	(005, 'EMPLOYEE_005', 75000, 'OPERATIONS');
    
SELECT * FROM EMPLOYEE;
SET SQL_SAFE_UPDATES = 0;
    
UPDATE EMPLOYEE 
SET SALARY = SALARY * 1.10 
WHERE DEPT = 'IT';

SELECT * FROM EMPLOYEE;

-- 14. Delete employees with salary < 30000.
DELETE 
FROM EMPLOYEE
WHERE SALARY < 30000;

-- 15. Get employees with salary > 50000.
SELECT * 
FROM EMPLOYEE AS E 
WHERE E.SALARY > 50000;

-- 16. Get employees whose name starts with A.
SELECT * 
FROM EMPLOYEE AS E 
WHERE E.EMPNAME LIKE 'A%';

-- 2479586_souptik
-- 17. Sort employees by salary desc.
SELECT * 
FROM EMPLOYEE AS E
ORDER BY SALARY DESC;

-- 18. Get Total, Average, and Highest Salary.
SELECT 
	COUNT(*) AS TOTAL , 
    AVG(SALARY) AS AVERAGE , 
    MAX(SALARY) AS HIGHEST_SALARY 
FROM EMPLOYEE AS E;

-- 19. Create Departments table and join it with Employees.
CREATE TABLE DEPARTMENTS (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(255)
);

INSERT INTO DEPARTMENTS VALUES
(101, 'HR'),
(102, 'FINANCE'),
(103, 'IT'),
(104, 'MARKETING'),
(105, 'OPERATIONS');


SELECT * FROM EMPLOYEE AS E 
INNER JOIN DEPARTMENTS AS D
ON E.DEPT = D.DEPT_NAME;

-- 20. Create stored procedure GetEmployeesByDept.
DELIMITER //
CREATE PROCEDURE GETEMPLOYEESBYDEPT( IN DEPTNAME VARCHAR(255))
BEGIN
	SELECT *
    FROM EMPLOYEE AS E
    WHERE E.DEPT = DEPTNAME;
END //
DELIMITER ;

CALL GETEMPLOYEESBYDEPT('IT');
